name: Automated tests
on: pull_request

jobs:
  jest:
    name: Jest Ubuntu
    runs-on: ubuntu-latest

    # Set up PostgreSQL service container
    services:
      postgres:
        image: postgres:latest
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 123
          POSTGRES_DB: nest_test
        ports:
          - 5432:5432
        # Health check ensures PostgreSQL is ready before tests run
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Use Node.JS 20.18.1
        uses: actions/setup-node@v4.1.0
        with:
          node-version: '20.18.1'

      - name: Install dependencies
        run: npm ci

      # Run Prisma migrations before tests
      - name: Apply database migrations
        run: npx prisma migrate deploy
        env:
          DATABASE_URL: postgresql://postgres:123@localhost:5432/nest_test

      # Generate Prisma client
      - name: Generate Prisma Client
        run: npx prisma generate

      - name: Check code style
        run: |
          npm run format:check || npm run format
          npm run lint
        continue-on-error: true

      - name: Run unit tests
        run: npm run test
        env:
          CI: true
          DATABASE_URL: postgresql://postgres:123@localhost:5432/nest_test

      - name: Run e2e tests
        run: npm run test:e2e
        env:
          CI: true
          DATABASE_URL: postgresql://postgres:123@localhost:5432/nest_test

      - name: Build application
        run: npm run build
