name: Automated tests

on: pull_request

jobs:
  jest:
    name: Jest Ubuntu
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4.2.2

      - name: Use Node.JS 20.18.1
        uses: actions/setup-node@v4.1.0
        with:
          node-version: "20.18.1"
      
      - name: install dependecies
        run: npm ci

      - run: npm test

      - name: Check code style
        run: |
          npm run format:check || npm run format
          npm run lint
        continue-on-error: true

      - name: Run tests
        run: |
          npm run test
          npm run test:e2e
        env:
          CI: true

      - name: Build application
        run: npm run build
